# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Продолжительность'),
        ),
    ]
