# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('mapping_type', 'name'),
                'verbose_name_plural': 'Attributes',
                'verbose_name': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='EntityAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name_plural': 'Entity attributes',
                'verbose_name': 'Entity attribute',
            },
        ),
        migrations.CreateModel(
            name='MappingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name_plural': 'MappingTypes',
                'verbose_name': 'MappingType',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='entity_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.EntityAttribute'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='mapping_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.MappingType'),
        ),
    ]
