# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityattribute',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
