# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_entityattribute_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtype',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='mappingtype',
            name='endpoint',
            field=models.URLField(blank=True, verbose_name='Endpoint'),
        ),
    ]
