# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_auto_20180711_1037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('mapping_type', 'name')]),
        ),
    ]
