# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_auto_20180711_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
