# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 15:35
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_bin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binitem',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='datetime'),
            preserve_default=False,
        ),
    ]
