# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_bin', '0002_binitem_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='binitem',
            name='url',
            field=models.CharField(default='/', max_length=2000, verbose_name='url'),
            preserve_default=False,
        ),
    ]
