# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_bin', '0003_binitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
