# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_bin', '0004_bin_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
