# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_bin', '0005_auto_20180221_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='binitem',
            name='type',
            field=models.CharField(choices=[('EL', 'ElasticSearch'), ('CS', 'CSV file'), ('JS', 'JSON file'), ('CU', 'CI')], default='EL', max_length=2),
        ),
    ]
