# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_bin', '0006_binitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binitem',
            name='type',
        ),
    ]
