# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_bin', '0007_remove_binitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together=set([('user', 'name')]),
        ),
    ]
